[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd server && npm ci"]

[phases.build]
cmds = ["cd server && npx prisma generate", "cd server && npm run build"]

[start]
cmd = "cd server && npm start"

